from whisper import load_model

# Tiny Model Loading...
load_model("tiny")
# Base Model Loading...
load_model("base")
# Small Model Loading...
load_model("small")
# Medium Model Loading...
load_model("medium")
# Large Model Loading...
load_model("large")
# Large-v2 Model Loading...
load_model("large-v2")